# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'iTraveler' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iTraveler
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  pod "FlagPhoneNumber"
  
  pod 'Alamofire', '~> 5.2'

end
