# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'PostPigeon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PostPigeon
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'

  pod 'MessageKit'
  pod 'SDWebImage', '~> 5.0'
  pod 'Alamofire', '~> 5.2'

  pod "FlagPhoneNumber"

end
